FROM node:alpine

WORKDIR /usr/app/

RUN npm install -g pm2

COPY ./secrets_microservice/package*.json ./
RUN npm install

COPY ./secrets_microservice/ ./

CMD [ "pm2-runtime", "npm", "--", "start" ]
